"""
Template content for files generated by `wv create`.
All templates are plain strings; variable substitution is done in commands/create.py.
"""

WV_TOML = """\
[project]
name = "{project_name}"
version = "{version}"
window_title = "{window_title}"
author = "{author}"

[build]
# Windows default path; ignored on non-Windows platforms
inno_setup_path = "C:/Program Files (x86)/Inno Setup 6/ISCC.exe"
"""

CONFIG_PY = """\
# Development mode: load index.html directly from frontend/dist
HTML_PATH_DEV = '../../frontend/dist/index.html'

# Packaged mode: PyInstaller bundles frontend/dist contents into _f_dist
HTML_PATH_APP = '_f_dist/index.html'

# Window title (injected from wv.toml at project creation time)
WINDOW_TITLE = "{window_title}"
"""

MAIN_PY = """\
import sys
import os
import webview
from config import WINDOW_TITLE, HTML_PATH_DEV, HTML_PATH_APP


def get_html_path() -> str:
    \"\"\"Resolve the correct HTML path depending on the runtime environment.\"\"\"
    if getattr(sys, 'frozen', False):
        # PyInstaller packaged environment: use sys._MEIPASS to locate resources
        base = sys._MEIPASS
        return os.path.join(base, HTML_PATH_APP)
    else:
        # Development / testing environment: use relative path to frontend/dist
        base = os.path.dirname(os.path.abspath(__file__))
        return os.path.join(base, HTML_PATH_DEV)


def main():
    from bridge.api import Api
    api = Api()
    window = webview.create_window(
        WINDOW_TITLE,
        url=get_html_path(),
        js_api=api,
    )
    webview.start()


if __name__ == '__main__':
    main()
"""

BRIDGE_INIT_PY = """\
# bridge package: pywebview JS API bridge classes live here
"""

BRIDGE_API_PY = """\
class Api:
    \"\"\"
    pywebview JS API example.
    The frontend calls methods of this class via window.pywebview.api.<method>().
    Add your own methods below and expose them to the Vue frontend.
    \"\"\"

    def greet(self, name: str) -> str:
        return f"Hello, {name}!"
"""

SPEC_FILE = """\
# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(
    ['../backend/src/main.py'],
    pathex=['../backend/src'],
    binaries=[],
    datas=[
        ('../frontend/dist', '_f_dist'),   # Bundle frontend build output
        ('../icon', 'icon'),               # Icon resources
    ],
    hiddenimports=['webview'],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='{project_name}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon='../icon/favicon.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='{project_name}',
)
"""

ISS_FILE = """\
[Setup]
AppName={project_name}
AppVersion={version}
DefaultDirName={{autopf}}\\{project_name}
DefaultGroupName={project_name}
OutputDir=publish
OutputBaseFilename={project_name}-{version}-setup
SetupIconFile=../icon/favicon.ico
Compression=lzma
SolidCompression=yes

[Files]
Source: "../build/dist/{project_name}/*"; DestDir: "{{app}}"; Flags: recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{project_name}"; Filename: "{{app}}\\{project_name}.exe"
Name: "{{commondesktop}}\\{project_name}"; Filename: "{{app}}\\{project_name}.exe"

[Run]
Filename: "{{app}}\\{project_name}.exe"; Description: "立即启动"; Flags: nowait postinstall skipifsilent
"""

ROOT_GITIGNORE = """\
# ── Build output ─────────────────────────────────────────────────────────────
build/dist/
build/publish/

# ── Frontend ──────────────────────────────────────────────────────────────────
frontend/dist/
frontend/node_modules/

# ── Backend ───────────────────────────────────────────────────────────────────
backend/.venv/
backend/__pycache__/
backend/**/__pycache__/

# ── OS / IDE ──────────────────────────────────────────────────────────────────
.DS_Store
Thumbs.db
.vscode/
.idea/
"""

BACKEND_GITIGNORE = """\
# Python
__pycache__/
*.py[cod]
*.pyo
*.pyd
*.egg
*.egg-info/

# Virtual environment (uv)
.venv/

# uv
.uv/
uv.lock

# Distribution
dist/
build/

# PyInstaller
*.spec.bak

# Testing
.pytest_cache/
.coverage
htmlcov/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
"""